channels:
- https://packages.qiime2.org/qiime2/2024.5/amplicon/passed
- conda-forge
- bioconda
- defaults
dependencies:
- qiime2-amplicon
- pip
  - q2_vizard@git+https://github.com/qiime2/q2-vizard.git
