{% set pkg_data = load_file_data('../../../../report.json') %}
{% set version = pkg_data['install'][0]['metadata']['version'] %}

package:
  name: q2-vizard
  version: {{ version }}

source:
  path: ../..

build:
  script: "$PYTHON" -m pip install --debug -v .

requirements:
  build:
    # nodejs is only necessary in the build phase - our build script needs it
    # in order to render out transpiled js assets for various visualizations.
    # once rendered, node is no longer necessary. don't set this in host reqs.
    - nodejs

  host:
    - python {{ python }}
    - pip
    - setuptools

  run:
    - python {{ python }}
    - pandas {{ pandas }}
    - jinja2
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2-stats {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - pytest

  imports:
    - q2_vizard
    - qiime2.plugins.vizard

  commands:
    - py.test --pyargs q2_vizard

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
