# WIP: working on a new GHA in distributions to pair with this
# that can be used by any community developers to implement CI

# name: ci-vizard
# on:
#   pull_request:
#     branches: ["dev"]
#   push:
#     branches: ["dev"]
# jobs:
#   ci:
#     uses: qiime2/distributions/.github/workflows/lib-community-ci.yaml@dev
#     with:
#       distro: amplicon
#       release-epoch: 2024.10
#       github-org-name: qiime2
#       github-repo-name: q2-vizard
#       github-env-ref: dev
#       env-file-name: 2024.5-vizard-environment.yml
